schema: "classroom50/repo-config/v1"
classroom: "swdevprac2-69-1"
assignment: "a09-swdevprac2-69-1"
secret: "cf2djm54"
owner:
  username: "santa-nathawat"
  id: 248125825
  accepted_at: "2026-10-08T14:13:33Z"
source:
  owner: "SWDevPrac2-69-1"
  owner_id: 312147402
  repo: "2110507_a09_starter"
  branch: "main"
